application: readlater
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /scripts/(.*\.js)
  static_files: static/scripts/\1
  upload: static/scripts/(.*\.js)

- url: /styles/(.*\.css)
  static_files: static/styles/\1
  upload: static/styles/(.*\.css)

- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
